"""initial schema

Revision ID: fbcb6c5a7f9b
Revises: 
Create Date: 2026-05-23 09:30:35.277501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbcb6c5a7f9b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('range_start', sa.Integer(), nullable=False),
    sa.Column('range_end', sa.Integer(), nullable=False),
    sa.Column('last_scanned', sa.String(), nullable=False),
    sa.Column('ticket_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cluster_range_end', 'clusters', ['range_end'], unique=False)
    op.create_index('idx_cluster_range_start', 'clusters', ['range_start'], unique=False)
    op.create_table('error_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('command', sa.String(), nullable=False),
    sa.Column('error_type', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('first_seen', sa.String(), nullable=False),
    sa.Column('last_seen', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_errors_command', 'error_logs', ['command'], unique=False)
    op.create_index('idx_errors_number', 'error_logs', ['number'], unique=False)
    op.create_index('idx_errors_resolved', 'error_logs', ['resolved'], unique=False)
    op.create_index('idx_errors_type', 'error_logs', ['error_type'], unique=False)
    op.create_table('locations',
    sa.Column('raw_location', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geocoded_at', sa.String(), nullable=False),
    sa.Column('ticket_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('raw_location')
    )
    op.create_index('idx_locations_lat_lon', 'locations', ['latitude', 'longitude'], unique=False)
    op.create_table('scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('range_start', sa.Integer(), nullable=False),
    sa.Column('range_end', sa.Integer(), nullable=False),
    sa.Column('until_date', sa.String(), nullable=False),
    sa.Column('tickets_found', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=False),
    sa.Column('duration_s', sa.Float(), nullable=False),
    sa.Column('scanned_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('ticket_number', sa.String(), nullable=False),
    sa.Column('ticket_key', sa.String(), nullable=False),
    sa.Column('vehicle_make', sa.String(), nullable=False),
    sa.Column('license_plate', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('violation', sa.String(), nullable=False),
    sa.Column('amount_due', sa.String(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('officer', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('ticket_type', sa.String(), nullable=False),
    sa.Column('raw_json', sa.String(), nullable=False),
    sa.Column('first_seen', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('ticket_number')
    )
    op.create_index('idx_tickets_issue_date', 'tickets', ['issue_date'], unique=False)
    op.create_index('idx_tickets_license_plate', 'tickets', ['license_plate'], unique=False)
    op.create_index('idx_tickets_location', 'tickets', ['location'], unique=False)
    op.create_index('idx_tickets_officer', 'tickets', ['officer'], unique=False)
    op.create_index('idx_tickets_status_state', 'tickets', ['status', 'state'], unique=False)
    op.create_index('idx_tickets_ticket_key', 'tickets', ['ticket_key'], unique=False)
    op.create_index('idx_tickets_updated_at', 'tickets', ['updated_at'], unique=False)
    op.create_index('idx_tickets_violation', 'tickets', ['violation'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tickets_violation', table_name='tickets')
    op.drop_index('idx_tickets_updated_at', table_name='tickets')
    op.drop_index('idx_tickets_ticket_key', table_name='tickets')
    op.drop_index('idx_tickets_status_state', table_name='tickets')
    op.drop_index('idx_tickets_officer', table_name='tickets')
    op.drop_index('idx_tickets_location', table_name='tickets')
    op.drop_index('idx_tickets_license_plate', table_name='tickets')
    op.drop_index('idx_tickets_issue_date', table_name='tickets')
    op.drop_table('tickets')
    op.drop_table('scans')
    op.drop_index('idx_locations_lat_lon', table_name='locations')
    op.drop_table('locations')
    op.drop_index('idx_errors_type', table_name='error_logs')
    op.drop_index('idx_errors_resolved', table_name='error_logs')
    op.drop_index('idx_errors_number', table_name='error_logs')
    op.drop_index('idx_errors_command', table_name='error_logs')
    op.drop_table('error_logs')
    op.drop_index('idx_cluster_range_start', table_name='clusters')
    op.drop_index('idx_cluster_range_end', table_name='clusters')
    op.drop_table('clusters')
    # ### end Alembic commands ###
